apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencode-web-redirect-data
  namespace: bot
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://bot-opencode-web.talesofai.com/L2RhdGE
    nginx.ingress.kubernetes.io/permanent-redirect-code: "302"
spec:
  ingressClassName: nginx
  rules:
    - host: bot-opencode-web.talesofai.com
      http:
        paths:
          - path: /data
            pathType: Exact
            backend:
              service:
                name: opencode-server
                port:
                  number: 4096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencode-web-redirect-session-data
  namespace: bot
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://bot-opencode-web.talesofai.com/L2RhdGE/session
    nginx.ingress.kubernetes.io/permanent-redirect-code: "302"
spec:
  ingressClassName: nginx
  rules:
    - host: bot-opencode-web.talesofai.com
      http:
        paths:
          - path: /session/data
            pathType: Exact
            backend:
              service:
                name: opencode-server
                port:
                  number: 4096
