apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencode-bot-agent-wiki
  namespace: bot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: opencode-web-auth
spec:
  ingressClassName: nginx
  rules:
    - host: world-wiki.talesofai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opencode-bot-agent-wiki
                port:
                  number: 8080
  tls:
    - hosts:
        - world-wiki.talesofai.com
      secretName: ssl-world-wiki.talesofai.com
